### ISSUE TITLE
AttributeError raised when using dynamically defined class

### ISSUE THREAD

**Issue by jakirkham** [wbolster/qualname#2]
Given the following file.

```
# classmaker.py
def f():
    return type('NewCls', (object,), dict())
```

Trying to get the qualified name fails.

```
>>> import qualname
>>> import classmaker
>>> qualname.qualname(classmaker.f())
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-03af44776c0f> in <module>()
----> 1 qualname.qualname(c)

/opt/conda/lib/python2.7/site-packages/qualname.pyc in qualname(obj)
     53             _, lineno = inspect.getsourcelines(obj)
     54         except (OSError, IOError):
---> 55             return obj.__qualname__  # raises a sensible error
     56     elif inspect.isfunction(obj) or inspect.ismethod(obj):
     57         if hasattr(obj, 'im_func'):

AttributeError: type object 'NewCls' has no attribute '__qualname__'
```

Trying to do so with the object stored also fails.

```
>>> c = classmaker.f()
>>> qualname.qualname(c)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-03af44776c0f> in <module>()
----> 1 qualname.qualname(c)

/opt/conda/lib/python2.7/site-packages/qualname.pyc in qualname(obj)
     53             _, lineno = inspect.getsourcelines(obj)
     54         except (OSError, IOError):
---> 55             return obj.__qualname__  # raises a sensible error
     56     elif inspect.isfunction(obj) or inspect.ismethod(obj):
     57         if hasattr(obj, 'im_func'):

AttributeError: type object 'NewCls' has no attribute '__qualname__'
```

When running the same sorts of things on Python 3.4.3, I see the following.

```
>>> classmaker.f().__qualname__
'NewCls'
>>> c.__qualname__
'NewCls'
```

**Comment by wbolster** [comment]
(Sorry for not answering earlier, I only noticed this issue just now.)

Can you try to reproduce this using a real source file instead of the interactive interpreter?

See https://github.com/wbolster/qualname#how-does-it-work  for why it needs source code.

**Comment by jakirkham** [comment]
Sure, please see code below.

```
# classmaker.py
import qualname

def f():
    cls = type('NewCls', (object,), dict())
    print(qualname.qualname(cls))

if __name__ == "__main__":
    f()
```

This can then be run via the CLI and gives the following traceback.

```
$ python classmaker.py
Traceback (most recent call last):
  File "classmaker.py", line 8, in <module>
    f()
  File "classmaker.py", line 5, in f
    print(qualname.qualname(cls))
  File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/qualname.py", line 55, in qualname
    return obj.__qualname__  # raises a sensible error
AttributeError: type object 'NewCls' has no attribute '__qualname__'
```

**Comment by wbolster** [comment]
fwiw, i do not think this can be done in py2 for all cases. this package is a hack (see readme) to make it work in som cases, but there is a reason the interpreter had to change in python 3 to make `__qualname__` work.
