### ISSUE TITLE
Taking qualnames of builtins fails on Py2

### ISSUE THREAD

**Issue by Julian** [wbolster/qualname#8]
E.g.:

```

?  ~[regret:python] -c 'from qualname import qualname; print(qualname(str))'                                                                                          julian@Air ?
Traceback (most recent call last):
  File "<module>", line 1, in <module>
  File "/Users/julian/.local/share/virtualenvs/regret/site-packages/qualname.py", line 50, in qualname
    return obj.__qualname__  # raises a sensible error
AttributeError: type object 'str' has no attribute '__qualname__'
```

whereas `twisted.python.reflect.fullyQualifiedName` (which is what I'm comparing to :) produces the expected:

```

?  ~[regret:python] -c 'from twisted.python.reflect import fullyQualifiedName as qualname; print(qualname(str))'                                                      julian@Air ?
__builtin__.str
```

(other than the fact that qualname isn't fully qualified :()

**Comment by alexmojaki** [comment]
I think in some cases `qualname` should fall back to `__name__`. In my projects I've got something like:

```python
def safe_qualname(x):
    try:
        return x.__qualname___
    except AttributeError:
        return x.__name__
```

This would also solve #2 as well.
